### ISSUE TITLE
Technical details area in Update Manager could look better

### ISSUE THREAD

**Issue by mivoligo** [ubuntu/communitheme#505]
I use Polish version of Ubuntu so I'm not sure if it really is "technical details" area. Anyway I'm talking about the bottom half part of the app.
![zrzut ekranu z 2018-06-01 09-25-05](https://user-images.githubusercontent.com/1629120/40830454-63559f02-657e-11e8-9f29-1610f72cba68.png)

**Comment by madsrh** [comment]
@mivoligo Do you mean the tab background - the color behind "Opis" in your screenshot?

**Comment by mivoligo** [comment]
Yes. Also the alignment of the elements. But I'm guessing it could be upstream problem, not communitheme specific. Next time I have updates, I will check how does it look in "normal" Ubuntu session.

**Comment by madsrh** [comment]
When looking at The Widget Factory, I actually think the correct solution would be to add a border around the tabs **and** the changelog viewer too:
![image](https://user-images.githubusercontent.com/3986894/40891933-581b6f96-678f-11e8-94af-6eef0c0e4c9a.png)

This looks a bit messy because we have a border inside a border 🤷‍♂️ 
![image](https://user-images.githubusercontent.com/3986894/40891918-07e9c414-678f-11e8-9c3d-6dee0374922c.png)
 
We can have a border round the top only, but then we would have to change the width of the changelog view, like below. This looks less busy, but tabs looks disconnected from the view log.

![image](https://user-images.githubusercontent.com/3986894/40892018-cc841170-6790-11e8-8135-619c684102fa.png)

**Comment by Paz-it** [comment]
A good example of how it may look we have in this page : 
![screenshot from 2018-06-05 16-44-37](https://user-images.githubusercontent.com/37431503/40979977-f8daa8ec-68df-11e8-96e4-e3600e6fcad0.png)
